### ISSUE TITLE
Unable to do initial `yarn` after cloning the repo down.

### ISSUE THREAD

**Issue by MaxOrelus** [Microsoft/TypeScript-React-Starter#26]
I've tried this several times to make sure it wasn't an off occurrence. When trying to install the dependencies, the runner exits and fails. 

![error](http://i.imgur.com/fn7rUnS.png)

```
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[1/1] ⢀ fsevents: node-pre-gyp
[-/1] ⢀ waiting...
[-/1] ⢀ waiting...
[-/1] ⢀ waiting...
warning Error running install script for optional dependency: "/Users/maxorelus/Sites/cr-ui/node_modules/fsevents: Command failed.\nExit code: 1\nCommand: sh\nArguments: -c node-pre-gyp install --fallback-to-build\nDirectory: /Users/maxorelus/Sites/cr-ui/node_modules/fsevents\nOutput:\nnode-pre-gyp info it worked if it ends with ok\nnode-pre-gyp info using node-pre-gyp@0.6.29\nnode-pre-gyp info using node@7.10.0 | darwin | x64\nnode-pre-gyp info check checked for \"/Users/maxorelus/Sites/cr-ui/node_modules/fsevents/lib/binding/Release/node-v51-darwin-x64/fse.node\" (not found)\nnode-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v51-darwin-x64.tar.gz\nnode-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v51-darwin-x64.tar.gz\nnode-pre-gyp ERR! Tried to download: https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v51-darwin-x64.tar.gz \nnode-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.14 and node@7.10.0 (node-v51 ABI) (falling back to source compile with node-gyp) \nnode-pre-gyp http Pre-built binary not available for your system, looked for https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v51-darwin-x64.tar.gz \nnode-pre-gyp ERR! build error \nnode-pre-gyp ERR! stack Error: Failed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)\nnode-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/maxorelus/Sites/cr-ui/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:77:29)\nnode-pre-gyp ERR! stack     at emitOne (events.js:96:13)\nnode-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)\nnode-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)\nnode-pre-gyp ERR! stack     at onErrorNT (internal/child_process.js:367:16)\nnode-pre-gyp ERR! stack     at _combinedTickCallback (internal/process/next_tick.js:80:11)\nnode-pre-gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:104:9)\nnode-pre-gyp ERR! System Darwin 16.6.0\nnode-pre-gyp ERR! command \"/usr/local/Cellar/node/7.10.0/bin/node\" \"/Users/maxorelus/Sites/cr-ui/node_modules/fsevents/node_modules/.bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"\nnode-pre-gyp success Saved lockfile.
✨  Done in 12.70s.
```

**System Specification**

* npm v4.6.1
* Node v7.10.0
* OSX Sierra

**Comment by DanielRosenwasser** [comment]
Strange, does a plain `npm install` work?

**Comment by MaxOrelus** [comment]
hmmmm.... that's strange. Regular `npm install` seems to work fine, but `yarn` doesn't. Thanks!
